Allow Tries to be pickled
Provide _Node.__getstate__ and Node.__setstate__ so that tries can be
pickled.  Without those methods, attepmts to pickle a trie result in:

	TypeError: a class that defines __slots__ without defining
	__getstate__ cannot be pickled

The implementation is rather straightforward reflecting directly _Node’s
structure.  For space efficiency, a more optimised representation could
be devised, but I don’t think that’s necessary.

Reported-by: Philippe Ombredanne <pombredanne@gmail.com>  # https://github.com/google/pygtrie/issues/7