Fix version.py failing to read git version
Fixe the following failure:

	Traceback (most recent call last):
	  File "version.py", line 129, in <module>
	    print(get_version())
	  File "version.py", line 122, in get_version
	    raise ValueError('Cannot find the version number')
	ValueError: Cannot find the version number

Which has been introduced by the previous commit ([2785d76: Make
version.py Python 3 compatible]).